In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains
import time
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.execute_script(
    "window.location = 'https://www.macrotrends.net/stocks/charts/GOOG/alphabet/cash-flow-statement?freq=A';")
driver.implicitly_wait(2)

grid = driver.find_element(By.ID, 'wrapperjqxgrid')
time.sleep(1)
driver.execute_script("window.scrollBy(0, 600);")
scrollbar = driver.find_element(By.ID, 'jqxScrollThumbhorizontalScrollBarjqxgrid')

time.sleep(1)

actions = ActionChains(driver)
time.sleep(1)

for i in range(1, 6):
    actions.drag_and_drop_by_offset(scrollbar, i * 70, 0).perform()
    time.sleep(1)

soup = BeautifulSoup(grid.get_attribute('outerHTML'), "html.parser")
headersList = soup.findAll('div', {'role': 'columnheader'})
col_names=[h.text for h in headersList]
divList = soup.findAll('div', {'role': 'row'})
data = [[x.text for x in div.findChildren('div', recursive=False)] for div in divList]
df = pd.DataFrame(data, columns=col_names)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    df

In [3]:
df

,Annual Data | Millions of US $ except per share data,,2019-12-31,2018-12-31,2017-12-31,2016-12-31,2015-12-31,2014-12-31,2013-12-31,2012-12-31,2011-12-31,2010-12-31,2009-12-31
0,Net Income/Loss,,$34 343,$30 736,$12 662,$19 478,$16 348,$14 136,$12 733,$10 737,$9 737,$8 505,$6 520
1,Total Depreciation And Amortization - Cash Flow,,$11 781,$9 035,$6 915,$6 144,$5 063,$4 979,$3 939,$2 962,$1 851,$1 396,$1 524
2,Other Non-Cash Items,,$7 577,$3 292,$8 268,$7 114,$5 570,$3 237,$1 831,$2 022,$2 347,$1 279,$786
3,Total Non-Cash Items,,$19 358,$12 327,$15 183,$13 258,$10 633,$8 216,$5 770,$4 984,$4 198,$2 675,$2 310
4,Change In Accounts Receivable,,$-4 340,$-2 169,$-3 768,$-2 578,$-2 094,$-1 641,$-1 307,$-787,$-1 156,$-1 129,$-504
5,Change In Inventories,,-,-,-,-,-,-,-,-,$-30,-,-
6,Change In Accounts Payable,,$428,$1 067,$731,$110,$203,$436,$605,$-499,$101,$272,$34
7,Change In Assets/Liabilities,,$-584,$-836,$-1 774,$535,$-275,$284,$-697,$-369,$-70,$-303,$338
8,Total Change In Assets/Liabilities,,$819,$4 908,$9 246,$3 300,$-409,$672,$156,$898,$630,$-99,$486
9,Cash Flow From Operating Activities,,$54 520,$47 971,$37 091,$36 036,$26 572,$23 024,$18 659,$16 619,$14 565,$11 081,$9 316
10,"Net Change In Property, Plant, And Equipment",,$-23 548,$-25 139,$-13 184,$-9 972,$-9 915,$-10 959,$-7 358,$-3 273,$-3 438,$-4 018,$-810
11,Net Change In Intangible Assets,,-,-,-,-,-,-,-,-,-,-,-
12,Net Acquisitions/Divestitures,,$-2 515,$-1 491,$-287,$-986,$-236,$-4 502,$1 077,$-10 568,$-1 900,$-1 067,$-108
13,Net Change In Short-term Investments,,$-2 490,$-1 651,$-18 236,$-17 614,$-11 463,$-4 995,$-7 130,$1 770,$-12 926,$-6 886,$-7 036
14,Net Change In Long-Term Investments,,$-1 527,$-321,$-1 212,$-165,$-1 747,$-2 002,$31,$-651,$-423,$-1 070,$-65
15,Net Change In Investments - Total,,$-4 017,$-1 972,$-19 448,$-17 779,$-13 210,$-6 997,$-7 099,$1 119,$-13 349,$-7 956,$-7 101
16,Investing Activities - Other,,$589,$98,$1 518,$-2 428,$-350,$1 403,$-299,$-334,$-354,$2 361,-
17,Cash Flow From Investing Activities,,$-29 491,$-28 504,$-31 401,$-31 165,$-23 711,$-21 055,$-13 679,$-13 056,$-19 041,$-10 680,$-8 019
18,Net Long-Term Debt,,$-268,$-61,$-86,$-1 335,$-23,$-18,$-557,$1 328,$726,$3 463,-
19,Net Current Debt,,-,-,-,-,-,-,-,-,-,-,-
20,Debt Issuance/Retirement Net - Total,,$-268,$-61,$-86,$-1 335,$-23,$-18,$-557,$1 328,$726,$3 463,-
21,Net Common Equity Issued/Repurchased,,$-18 176,$-8 125,$-4 046,$-3 693,$-1 780,-,-,-,-,$-801,-
22,Net Total Equity Issued/Repurchased,,$-18 176,$-8 125,$-4 046,$-3 693,$-1 780,-,-,-,-,$-801,-
23,Total Common And Preferred Stock Dividends Paid,,-,-,-,-,-,-,-,-,-,-,-
24,Financial Activities - Other,,$-4 765,$-4 993,$-4 166,$-3 304,$-2 422,$-2 069,$-300,$-99,$81,$388,$233
25,Cash Flow From Financial Activities,,$-23 209,$-13 179,$-8 298,$-8 332,$-4 225,$-2 087,$-857,$1 229,$807,$3 050,$233
26,Net Cash Flow,,$1 797,$5 986,$-2 203,$-3 631,$-1 798,$-551,$4 120,$4 795,$-3 647,$3 432,$1 541
27,Stock-Based Compensation,,$10 794,$9 353,$7 679,$6 703,$5 203,$4 279,$3 343,$2 692,$1 974,$1 376,$1 164
28,Common Stock Dividends Paid,,-,-,-,-,-,-,-,-,-,-,-