In [2]:
!pip install pytickersymbols

Collecting pytickersymbols

[notice] A new release of pip is available: 23.3 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading pytickersymbols-1.13.0-py3-none-any.whl (79 kB)
     -------------------------------------- 79.5/79.5 kB 261.4 kB/s eta 0:00:00
Collecting wheel==0.38.4 (from pytickersymbols)
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting PyYAML==6.0 (from pytickersymbols)
  Downloading PyYAML-6.0-cp37-cp37m-win_amd64.whl (153 kB)
     ------------------------------------ 153.2/153.2 kB 212.7 kB/s eta 0:00:00
Requirement already satisfied: packaging in d:\python\lib\site-packages (from pytickersymbols) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in d:\python\lib\site-packages (from packaging->pytickersymbols) (2.4.7)
Installing collected packages: wheel, PyYAML, pytickersymbols
  Attempting uninstall: wheel
    Found existing installation: wheel 0.36.2
    Uninstalling wheel-0.36.2:
      Successfully uninstalled wheel-0.36.2
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.4.1
    Uninstalling PyYAML-5.4.1:
      Successfully uninstalled PyYAML-5.4.1
Successfully installed PyYAML-6.0 pytickersymbols-1.13.0 wheel-0.38.4

In [20]:
from pytickersymbols import PyTickerSymbols

In [21]:
stock_data = PyTickerSymbols()
sp100_stocks = stock_data.get_stocks_by_index('S&P 100')
print(list(sp100_stocks))

[{'name': 'Linde PLC', 'symbol': 'LIN', 'country': 'United Kingdom', 'indices': ['DAX', 'EURO STOXX 50', 'S&P 100', 'S&P 500'], 'industries': ['Commodity Chemicals', 'Basic Materials', 'Chemicals'], 'symbols': [{'yahoo': 'LIN.F', 'google': 'FRA:LIN', 'currency': 'EUR'}, {'yahoo': 'LIN', 'google': 'NYSE:LIN', 'currency': 'USD'}], 'metadata': {'founded': 1879, 'employees': 74207}, 'isins': ['IE00BZ12WP82'], 'akas': []}, {'name': '3M Company', 'symbol': 'MMM', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Industrials', 'Industrial Conglomerates'], 'symbols': [{'yahoo': 'MMM.F', 'google': 'FRA:MMM', 'currency': 'EUR'}, {'yahoo': 'MMM', 'google': 'NYSE:MMM', 'currency': 'USD'}], 'metadata': {'founded': 1902, 'employees': 94987}, 'isins': ['US88579Y1010'], 'akas': []}, {'name': 'American Express Company', 'symbol': 'AXP', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Banking & Investment Services', 'Banking Services', 'Financials', 'Consumer Lending'], 'symbols': [{'yahoo': 'AEC1.F', 'google': 'FRA:AEC1', 'currency': 'EUR'}, {'yahoo': 'AXP', 'google': 'NYSE:AXP', 'currency': 'USD'}, {'yahoo': '0R3C.L', 'google': 'LON:0R3C', 'currency': 'GBP'}], 'metadata': {'founded': 1850, 'employees': 63700}, 'isins': [], 'akas': []}, {'name': 'Apple Inc.', 'symbol': 'AAPL', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Computers, Phones & Household Electronics', 'Technology', 'Technology Equipment', 'Phones & Handheld Devices'], 'symbols': [{'yahoo': 'APC.F', 'google': 'FRA:APC', 'currency': 'EUR'}, {'yahoo': 'AAPL', 'google': 'NASDAQ:AAPL', 'currency': 'USD'}], 'metadata': {'founded': 1976, 'employees': 147000}, 'isins': ['US0378331005'], 'akas': []}, {'name': 'The Boeing Company', 'symbol': 'BA', 'country': 'United States', 'indices': ['CAC 40', 'DOW JONES', 'EURO STOXX 50', 'S&P 100', 'S&P 500'], 'industries': ['Industrial Goods', 'Industrials', 'Aerospace & Defense'], 'symbols': [{'yahoo': 'BCO.F', 'google': 'FRA:BCO', 'currency': 'EUR'}, {'yahoo': 'BA', 'google': 'NYSE:BA', 'currency': 'USD'}, {'yahoo': 'BOE.L', 'google': 'LON:BOE', 'currency': 'GBP'}], 'metadata': {'founded': 1916, 'employees': 141014}, 'isins': ['NL0000235190'], 'akas': []}, {'name': 'Caterpillar Inc.', 'symbol': 'CAT', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Industrial Goods', 'Industrials', 'Heavy Machinery & Vehicles', 'Machinery, Equipment & Components'], 'symbols': [{'yahoo': 'CAT1.F', 'google': 'FRA:CAT1', 'currency': 'EUR'}, {'yahoo': 'CAT', 'google': 'NYSE:CAT', 'currency': 'USD'}, {'yahoo': '0Q18.L', 'google': 'LON:0Q18', 'currency': 'GBP'}], 'metadata': {'founded': 1925, 'employees': 102300}, 'isins': [], 'akas': []}, {'name': 'Chevron Corporation', 'symbol': 'CVX', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Energy', 'Fossil Fuels', 'Oil & Gas'], 'symbols': [{'yahoo': 'CHV.F', 'google': 'FRA:CHV', 'currency': 'EUR'}, {'yahoo': 'CVX', 'google': 'NYSE:CVX', 'currency': 'USD'}], 'metadata': {'founded': 1879, 'employees': 44679}, 'isins': ['US1667641005'], 'akas': []}, {'name': 'Cisco Systems Inc.', 'symbol': 'CSCO', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Technology Equipment', 'Communications & Networking'], 'symbols': [{'yahoo': 'CIS.F', 'google': 'FRA:CIS', 'currency': 'EUR'}, {'yahoo': 'CSCO', 'google': 'NASDAQ:CSCO', 'currency': 'USD'}], 'metadata': {'founded': 1984, 'employees': 77500}, 'isins': [], 'akas': []}, {'name': 'The Coca-Cola Company', 'symbol': 'KO', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Food & Beverages', 'Consumer Non-Cyclicals', 'Beverages', 'Non-Alcoholic Beverages'], 'symbols': [{'yahoo': 'CCC3.F', 'google': 'FRA:CCC3', 'currency': 'EUR'}, {'yahoo': 'KO', 'google': 'OTCMKTS:KO', 'currency': 'USD'}], 'metadata': {'founded': 1892, 'employees': 86200}, 'isins': ['US1912161007'], 'akas': []}, {'name': 'Exxon Mobil Corporation', 'symbol': 'XOM', 'country': 'United States', 'indices': ['S&P 100', 'S&P 500'], 'industries': ['Energy', 'Fossil Fuels', 'Oil & Gas'], 'symbols': [{'yahoo': 'XONA.F', 'google': 'FRA:XONA', 'currency': 'EUR'}, {'yahoo': 'XOM', 'google': 'NYSE:XOM', 'currency': 'USD'}, {'yahoo': 'XON', 'google': 'NYSE:XON', 'currency': 'USD'}], 'metadata': {'founded': 1999, 'employees': 72000}, 'isins': ['US30231G1022'], 'akas': []}, {'name': 'The Goldman Sachs Group Inc.', 'symbol': 'GS', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Banking & Investment Services', 'Investment Banking & Investment Services', 'Financials', 'Investment Banking & Brokerage Services'], 'symbols': [{'yahoo': 'GOS.F', 'google': 'FRA:GOS', 'currency': 'EUR'}, {'yahoo': 'GS-PK', 'google': 'NYSE:GS', 'currency': 'USD'}, {'yahoo': 'GS', 'google': 'NYSE:GS', 'currency': 'USD'}, {'yahoo': 'GOS0.F', 'google': 'FRA:GOS0', 'currency': 'EUR'}], 'metadata': {'founded': 1869, 'employees': 40500}, 'isins': ['US38141G1040'], 'akas': []}, {'name': 'The Home Depot Inc.', 'symbol': 'HD', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Retailers', 'Specialty Retailers', 'Home Improvement Products & Services Retailers', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'HDI.F', 'google': 'FRA:HDI', 'currency': 'EUR'}, {'yahoo': 'HD', 'google': 'NYSE:HD', 'currency': 'USD'}, {'yahoo': 'HDI0.F', 'google': 'FRA:HDI0', 'currency': 'EUR'}], 'metadata': {'founded': 1978, 'employees': 400000}, 'isins': [], 'akas': []}, {'name': 'International Business Machines Corporation', 'symbol': 'IBM', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Software & IT Services', 'IT Services & Consulting'], 'symbols': [{'yahoo': 'IBM.F', 'google': 'FRA:IBM', 'currency': 'EUR'}, {'yahoo': 'IBM', 'google': 'NYSE:IBM', 'currency': 'USD'}, {'yahoo': 'IBM.L', 'google': 'LON:IBM', 'currency': 'GBP'}, {'yahoo': 'IBM0.F', 'google': 'FRA:IBM0', 'currency': 'EUR'}], 'metadata': {'founded': 1911, 'employees': 345900}, 'isins': ['US4592001014'], 'akas': []}, {'name': 'Intel Corporation', 'symbol': 'INTC', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Technology Equipment', 'Semiconductors & Semiconductor Equipment', 'Semiconductors'], 'symbols': [{'yahoo': 'INL.F', 'google': 'FRA:INL', 'currency': 'EUR'}, {'yahoo': 'INTC', 'google': 'NASDAQ:INTC', 'currency': 'USD'}], 'metadata': {'founded': 1968, 'employees': 110600}, 'isins': [], 'akas': []}, {'name': 'Johnson & Johnson', 'symbol': 'JNJ', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Pharmaceuticals', 'Pharmaceuticals & Medical Research', 'Healthcare'], 'symbols': [{'yahoo': 'JNJ.F', 'google': 'FRA:JNJ', 'currency': 'EUR'}, {'yahoo': 'JNJ', 'google': 'NYSE:JNJ', 'currency': 'USD'}], 'metadata': {'founded': 1886, 'employees': 132200}, 'isins': ['US4781601046'], 'akas': []}, {'name': 'JPMorgan Chase & Co.', 'symbol': 'JPM', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Banking & Investment Services', 'Banking Services', 'Financials', 'Banks'], 'symbols': [{'yahoo': 'CMC.F', 'google': 'FRA:CMC', 'currency': 'EUR'}, {'yahoo': 'JPM', 'google': 'NYSE:JPM', 'currency': 'USD'}], 'metadata': {'founded': 2000, 'employees': 255351}, 'isins': ['US46625H1005'], 'akas': []}, {'name': "McDonald's Corporation", 'symbol': 'MCD', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Hotels & Entertainment Services', 'Restaurants & Bars', 'Cyclical Consumer Services', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'MDO.F', 'google': 'FRA:MDO', 'currency': 'EUR'}, {'yahoo': 'MCD', 'google': 'NYSE:MCD', 'currency': 'USD'}, {'yahoo': 'MDO0.F', 'google': 'FRA:MDO0', 'currency': 'EUR'}], 'metadata': {'founded': 1940, 'employees': 210000}, 'isins': ['US5801351017'], 'akas': []}, {'name': 'Nike, Inc.', 'wiki_name': 'Nike, Inc.', 'symbol': 'NKE', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Apparel', 'Accessories', 'Sports equipment'], 'symbols': [{'yahoo': 'NKE.F', 'google': 'FRA:NKE', 'currency': 'EUR'}, {'yahoo': 'NKE', 'google': 'NYSE:NKE', 'currency': 'USD'}], 'metadata': {'founded': 1964, 'employees': 73300}, 'isins': ['US6541061031'], 'akas': []}, {'name': 'Merck & Co. Inc.', 'symbol': 'MRK', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Pharmaceuticals', 'Pharmaceuticals & Medical Research', 'Healthcare'], 'symbols': [{'yahoo': 'MRK', 'google': 'NYSE:MRK', 'currency': 'USD'}], 'metadata': {'founded': 1668, 'employees': 74000}, 'isins': [], 'akas': []}, {'name': 'Microsoft Corporation', 'symbol': 'MSFT', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Software', 'Technology', 'Software & IT Services'], 'symbols': [{'yahoo': 'MSF.F', 'google': 'FRA:MSF', 'currency': 'EUR'}, {'yahoo': 'MSFT', 'google': 'NASDAQ:MSFT', 'currency': 'USD'}, {'yahoo': 'MSF0.F', 'google': 'FRA:MSF0', 'currency': 'EUR'}], 'metadata': {'founded': 1975, 'employees': 166475}, 'isins': ['US5949181045'], 'akas': []}, {'name': 'Pfizer Inc.', 'symbol': 'PFE', 'country': 'United States', 'indices': ['S&P 100', 'S&P 500'], 'industries': ['Pharmaceuticals', 'Pharmaceuticals & Medical Research', 'Healthcare'], 'symbols': [{'yahoo': 'PFE.F', 'google': 'FRA:PFE', 'currency': 'EUR'}, {'yahoo': 'PFE', 'google': 'NYSE:PFE', 'currency': 'USD'}], 'metadata': {'founded': 1849, 'employees': 78500}, 'isins': [], 'akas': []}, {'name': 'The Procter & Gamble Company', 'symbol': 'PG', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Consumer Non-Cyclicals', 'Personal Products', 'Personal & Household Products & Services'], 'symbols': [{'yahoo': 'PRG.F', 'google': 'FRA:PRG', 'currency': 'EUR'}, {'yahoo': 'PG', 'google': 'NYSE:PG', 'currency': 'USD'}, {'yahoo': '0NOF.L', 'google': 'LON:0NOF', 'currency': 'GBP'}], 'metadata': {'founded': 1837, 'employees': 99000}, 'isins': [], 'akas': []}, {'name': 'UnitedHealth Group Inc.', 'symbol': 'UNH', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Managed Health care', 'Healthcare', 'Healthcare Providers & Services', 'Healthcare Services'], 'symbols': [{'yahoo': 'UNH.F', 'google': 'FRA:UNH', 'currency': 'EUR'}, {'yahoo': 'UNH', 'google': 'NYSE:UNH', 'currency': 'USD'}], 'metadata': {'founded': 1977, 'employees': 330000}, 'isins': [], 'akas': []}, {'name': 'Verizon Communications Inc.', 'symbol': 'VZ', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Telecommunications Services', 'Integrated Telecommunications Services'], 'symbols': [{'yahoo': 'BAC.F', 'google': 'FRA:BAC', 'currency': 'EUR'}, {'yahoo': 'VZ', 'google': 'NYSE:VZ', 'currency': 'USD'}], 'metadata': {'founded': 1983, 'employees': 132200}, 'isins': ['US92343V1044'], 'akas': []}, {'name': 'Visa Inc.', 'symbol': 'V', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Software & IT Services', 'Internet Services'], 'symbols': [{'yahoo': '3V64.F', 'google': 'FRA:3V64', 'currency': 'EUR'}, {'yahoo': 'V', 'google': 'NYSE:V', 'currency': 'USD'}, {'yahoo': '3V6.F', 'google': 'FRA:3V6', 'currency': 'EUR'}], 'metadata': {'founded': 1958, 'employees': 20500}, 'isins': [], 'akas': []}, {'name': 'Walmart Inc.', 'symbol': 'WMT', 'country': 'United States', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Consumer Non-Cyclicals', 'Food & Drug Retailing', 'Food Retail & Distribution'], 'symbols': [{'yahoo': 'WMT.F', 'google': 'FRA:WMT', 'currency': 'EUR'}, {'yahoo': 'WMT', 'google': 'NYSE:WMT', 'currency': 'USD'}, {'yahoo': 'WMTD.F', 'google': 'FRA:WMTD', 'currency': 'EUR'}], 'metadata': {'founded': 1962, 'employees': 22}, 'isins': ['US9311421039'], 'akas': []}, {'name': 'Walgreens Boots Alliance Inc.', 'symbol': 'WBA', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Consumer Non-Cyclicals', 'Food & Drug Retailing', 'Drug Retailers'], 'symbols': [{'yahoo': 'W8A.F', 'google': 'FRA:W8A', 'currency': 'EUR'}, {'yahoo': 'WBA', 'google': 'NASDAQ:WBA', 'currency': 'USD'}, {'yahoo': '0LSZ.L', 'google': 'LON:0LSZ', 'currency': 'GBP'}], 'metadata': {'founded': 2014, 'employees': 450000}, 'isins': [], 'akas': []}, {'name': 'The Walt Disney Company', 'symbol': 'DIS', 'country': 'United States', 'indices': ['S&P 100', 'S&P 500', 'DOW JONES'], 'industries': ['Media & Publishing', 'Cyclical Consumer Services', 'Broadcasting', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'WDP.F', 'google': 'FRA:WDP', 'currency': 'EUR'}, {'yahoo': 'DIS', 'google': 'OTCMKTS:DIS', 'currency': 'USD'}, {'yahoo': 'WDP0.F', 'google': 'FRA:WDP0', 'currency': 'EUR'}], 'metadata': {'founded': 1923, 'employees': 223000}, 'isins': ['US2546871060'], 'akas': []}, {'name': 'Adobe Inc.', 'symbol': 'ADBE', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Software', 'Technology', 'Software & IT Services'], 'symbols': [{'yahoo': 'ADB.F', 'google': 'FRA:ADB', 'currency': 'EUR'}, {'yahoo': 'ADBE', 'google': 'NASDAQ:ADBE', 'currency': 'USD'}], 'metadata': {'founded': 1982, 'employees': ''}, 'isins': [], 'akas': []}, {'name': 'Alphabet Inc.', 'symbol': 'GOOGL', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Software & IT Services', 'Internet Services'], 'symbols': [{'yahoo': 'ABEC.F', 'google': 'FRA:ABEC', 'currency': 'EUR'}, {'yahoo': 'GOOGL', 'google': 'NASDAQ:GOOGL', 'currency': 'USD'}, {'yahoo': 'ABEA.F', 'google': 'FRA:ABEA', 'currency': 'EUR'}, {'yahoo': 'GOOG', 'google': 'NASDAQ:GOOG', 'currency': 'USD'}], 'metadata': {'founded': 2015, 'employees': 135301}, 'isins': ['US02079K1079', 'US02079K3059'], 'akas': []}, {'name': 'Amazon.com Inc.', 'symbol': 'AMZN', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Diversified Retail', 'Retailers', 'Department Stores', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'AMZ.F', 'google': 'FRA:AMZ', 'currency': 'EUR'}, {'yahoo': 'AMZN', 'google': 'NASDAQ:AMZN', 'currency': 'USD'}], 'metadata': {'founded': 1994, 'employees': 1298000}, 'isins': ['US0231351067'], 'akas': []}, {'name': 'Amgen Inc.', 'symbol': 'AMGN', 'country': 'United States', 'indices': ['DOW JONES', 'NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Pharmaceuticals', 'Pharmaceuticals & Medical Research', 'Healthcare'], 'symbols': [{'yahoo': 'AMG.F', 'google': 'FRA:AMG', 'currency': 'EUR'}, {'yahoo': 'AMGN', 'google': 'NASDAQ:AMGN', 'currency': 'USD'}], 'metadata': {'founded': 1980, 'employees': 22000}, 'isins': ['US0311621009'], 'akas': []}, {'name': 'Charter Communications Inc.', 'symbol': 'CHTR', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Media & Publishing', 'Cyclical Consumer Services', 'Broadcasting', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'CQD.F', 'google': 'FRA:CQD', 'currency': 'EUR'}, {'yahoo': 'CHTR', 'google': 'NASDAQ:CHTR', 'currency': 'USD'}, {'yahoo': '0HW4.L', 'google': 'LON:0HW4', 'currency': 'GBP'}], 'metadata': {'founded': 1993, 'employees': 98000}, 'isins': [], 'akas': []}, {'name': 'Comcast Corporation', 'symbol': 'CMCSA', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Media & Publishing', 'Cyclical Consumer Services', 'Broadcasting', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'CTP2.F', 'google': 'FRA:CTP2', 'currency': 'EUR'}, {'yahoo': 'CMCSA', 'google': 'NASDAQ:CMCSA', 'currency': 'USD'}], 'metadata': {'founded': 1963, 'employees': 190000}, 'isins': [], 'akas': []}, {'name': 'Costco Wholesale Corporation', 'symbol': 'COST', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Diversified Retail', 'Retailers', 'Discount Stores', 'Consumer Cyclicals'], 'symbols': [{'yahoo': 'CTO.F', 'google': 'FRA:CTO', 'currency': 'EUR'}, {'yahoo': 'COST', 'google': 'NASDAQ:COST', 'currency': 'USD'}, {'yahoo': '0I47.L', 'google': 'LON:0I47', 'currency': 'GBP'}, {'yahoo': 'CTO0.F', 'google': 'FRA:CTO0', 'currency': 'EUR'}], 'metadata': {'founded': 1976, 'employees': 273000}, 'isins': [], 'akas': []}, {'name': 'Gilead Sciences Inc.', 'symbol': 'GILD', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Biotechnology & Medical Research', 'Pharmaceuticals & Medical Research', 'Healthcare'], 'symbols': [{'yahoo': 'GIS.F', 'google': 'FRA:GIS', 'currency': 'EUR'}, {'yahoo': 'GILD', 'google': 'NASDAQ:GILD', 'currency': 'USD'}], 'metadata': {'founded': 1987, 'employees': 11800}, 'isins': [], 'akas': []}, {'name': 'The Kraft Heinz Company', 'symbol': 'KHC', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Food & Beverages', 'Consumer Non-Cyclicals', 'Food Processing', 'Food & Tobacco'], 'symbols': [{'yahoo': 'KHNZ.F', 'google': 'FRA:KHNZ', 'currency': 'EUR'}, {'yahoo': 'KHC', 'google': 'NASDAQ:KHC', 'currency': 'USD'}, {'yahoo': '0JRV.L', 'google': 'LON:0JRV', 'currency': 'GBP'}], 'metadata': {'founded': 2015, 'employees': 38757}, 'isins': [], 'akas': []}, {'name': 'Mondelez International Inc.', 'symbol': 'MDLZ', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Food & Beverages', 'Consumer Non-Cyclicals', 'Food Processing', 'Food & Tobacco'], 'symbols': [{'yahoo': 'KTF.F', 'google': 'FRA:KTF', 'currency': 'EUR'}, {'yahoo': 'MDLZ', 'google': 'NASDAQ:MDLZ', 'currency': 'USD'}, {'yahoo': '0R0G.L', 'google': 'LON:0R0G', 'currency': 'GBP'}], 'metadata': {'founded': 1923, 'employees': 80000}, 'isins': [], 'akas': []}, {'name': 'Netflix Inc.', 'symbol': 'NFLX', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Software & IT Services', 'Internet Services'], 'symbols': [{'yahoo': 'NFC.F', 'google': 'FRA:NFC', 'currency': 'EUR'}, {'yahoo': 'NFLX', 'google': 'NASDAQ:NFLX', 'currency': 'USD'}, {'yahoo': 'NFC1.F', 'google': 'FRA:NFC1', 'currency': 'EUR'}], 'metadata': {'founded': 1997, 'employees': 12135}, 'isins': [], 'akas': []}, {'name': 'NVIDIA Corporation', 'symbol': 'NVDA', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Technology Equipment', 'Semiconductors & Semiconductor Equipment', 'Semiconductors'], 'symbols': [{'yahoo': 'NVD.F', 'google': 'FRA:NVD', 'currency': 'EUR'}, {'yahoo': 'NVDA', 'google': 'NASDAQ:NVDA', 'currency': 'USD'}, {'yahoo': 'NVDG.F', 'google': 'FRA:NVDG', 'currency': 'EUR'}], 'metadata': {'founded': 1993, 'employees': 18100}, 'isins': [], 'akas': []}, {'name': 'PayPal Holdings Inc.', 'symbol': 'PYPL', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Software & IT Services', 'Internet Services'], 'symbols': [{'yahoo': '2PP.F', 'google': 'FRA:2PP', 'currency': 'EUR'}, {'yahoo': 'PYPL', 'google': 'NASDAQ:PYPL', 'currency': 'USD'}, {'yahoo': '2PP0.F', 'google': 'FRA:2PP0', 'currency': 'EUR'}], 'metadata': {'founded': 1998, 'employees': 21800}, 'isins': [], 'akas': []}, {'name': 'Qualcomm Inc.', 'symbol': 'QCOM', 'country': 'United States', 'indices': ['NASDAQ 100', 'S&P 100', 'S&P 500'], 'industries': ['Technology', 'Technology Equipment', 'Semiconductors & Semiconductor Equipment', 'Semiconductors'], 'symbols': [{'yahoo': 'QCI.F', 'google': 'FRA:QCI', 'currency': 'EUR'}, {'yahoo': 'QCOM', 'google': 'NASDAQ:QCOM', 'currency': 'USD'}], 'metadata': {'founded': 1985, 'employees': 41

In [24]:
import pandas as pd
sp100_stocks = stock_data.get_stocks_by_index('S&P 100')
df_stock_tickers = pd.DataFrame(list(sp100_stocks))
df_stock_tickers.head()

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
0,Linde PLC,LIN,United Kingdom,"[DAX, EURO STOXX 50, S&P 100, S&P 500]","[Commodity Chemicals, Basic Materials, Chemicals]","[{'yahoo': 'LIN.F', 'google': 'FRA:LIN', 'curr...","{'founded': 1879, 'employees': 74207}",[IE00BZ12WP82],[],NaN
1,3M Company,MMM,United States,"[DOW JONES, S&P 100, S&P 500]","[Industrials, Industrial Conglomerates]","[{'yahoo': 'MMM.F', 'google': 'FRA:MMM', 'curr...","{'founded': 1902, 'employees': 94987}",[US88579Y1010],[],NaN
2,American Express Company,AXP,United States,"[DOW JONES, S&P 100, S&P 500]","[Banking & Investment Services, Banking Servic...","[{'yahoo': 'AEC1.F', 'google': 'FRA:AEC1', 'cu...","{'founded': 1850, 'employees': 63700}",[],[],NaN
3,Apple Inc.,AAPL,United States,"[DOW JONES, NASDAQ 100, S&P 100, S&P 500]","[Computers, Phones & Household Electronics, Te...","[{'yahoo': 'APC.F', 'google': 'FRA:APC', 'curr...","{'founded': 1976, 'employees': 147000}",[US0378331005],[],NaN
4,The Boeing Company,BA,United States,"[CAC 40, DOW JONES, EURO STOXX 50, S&P 100, S&...","[Industrial Goods, Industrials, Aerospace & De...","[{'yahoo': 'BCO.F', 'google': 'FRA:BCO', 'curr...","{'founded': 1916, 'employees': 141014}",[NL0000235190],[],NaN

In [25]:
df_stock_tickers.describe()

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
count,100,100,100,100,100,100,100,100,100,6
unique,100,100,4,8,55,100,100,39,1,6
top,Linde PLC,LIN,United States,"[S&P 100, S&P 500]","[Pharmaceuticals, Pharmaceuticals & Medical Re...","[{'yahoo': 'LIN.F', 'google': 'FRA:LIN', 'curr...","{'founded': 1879, 'employees': 74207}",[],[],"Nike, Inc."
freq,1,1,96,46,7,1,1,62,100,1

In [34]:
df_stock_tickers[['name','symbol']]

                            name symbol
0                      Linde PLC    LIN
1                     3M Company    MMM
2       American Express Company    AXP
3                     Apple Inc.   AAPL
4             The Boeing Company     BA
..                           ...    ...
95                      Dow Inc.    DOW
96  General Dynamics Corporation     GD
97   Lockheed Martin Corporation    LMT
98                 PepsiCo, Inc.    PEP
99          Meta Platforms, Inc.   META

[100 rows x 2 columns]

In [39]:
df_stock_tickers.to_csv('tickers.csv')

S&P 500 constituent Deere & Co. (NYSE:DE) will replace Walgreens Boots Alliance Inc. (NASD:WBA) in the S&P 100. Walgreens Boots Alliance is no longer representative of the mega-cap market space. Walgreens Boots Alliance will remain in the S&P 500.

In [40]:
import pandas as pd
sp500_stocks = stock_data.get_stocks_by_index('S&P 500')
df_stock_tickers_full = pd.DataFrame(list(sp500_stocks))
df_stock_tickers_full.head()

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
0,Linde PLC,LIN,United Kingdom,"[DAX, EURO STOXX 50, S&P 100, S&P 500]","[Commodity Chemicals, Basic Materials, Chemicals]","[{'yahoo': 'LIN.F', 'google': 'FRA:LIN', 'curr...","{'founded': 1879, 'employees': 74207}",[IE00BZ12WP82],[],NaN
1,Carnival Corporation,CCL,United Kingdom,[S&P 500],"[Hotels & Entertainment Services, Cyclical Con...","[{'yahoo': 'CVC1.F', 'google': 'FRA:CVC1', 'cu...","{'founded': 1972, 'employees': 150000}","[GB0031215220, PA1436583006]",[],NaN
2,STERIS PLC,SSE,United Kingdom,[S&P 500],"[Electric Utilities, Electric Utilities & IPPs...","[{'yahoo': '2TG.F', 'google': 'FRA:2TG', 'curr...","{'founded': 1985, 'employees': 12000}","[IE00BFY8C754, US8591521005]",[],NaN
3,3M Company,MMM,United States,"[DOW JONES, S&P 100, S&P 500]","[Industrials, Industrial Conglomerates]","[{'yahoo': 'MMM.F', 'google': 'FRA:MMM', 'curr...","{'founded': 1902, 'employees': 94987}",[US88579Y1010],[],NaN
4,American Express Company,AXP,United States,"[DOW JONES, S&P 100, S&P 500]","[Banking & Investment Services, Banking Servic...","[{'yahoo': 'AEC1.F', 'google': 'FRA:AEC1', 'cu...","{'founded': 1850, 'employees': 63700}",[],[],NaN

In [41]:
df_stock_tickers_full.describe()

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
count,499,499,499,499,499,499,499,499,499,88
unique,499,498,9,11,154,498,494,105,1,88
top,Linde PLC,DOW,United States,[S&P 500],[],[],"{'founded': 1911, 'employees': 92000}",[],[],"Nike, Inc."
freq,1,2,473,350,24,2,2,395,499,1

In [43]:
df_stock_tickers_full[(df_stock_tickers_full["symbol"]=='DE')]

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
214,Deere & Company,DE,United States,[S&P 500],"[Industrial Goods, Industrials, Heavy Machiner...","[{'yahoo': 'DCO.F', 'google': 'FRA:DCO', 'curr...","{'founded': 1837, 'employees': 69600}",[],[],NaN

In [45]:
df_stock_tickers[(df_stock_tickers["symbol"]=='DE')]

Empty DataFrame
Columns: [name, symbol, country, indices, industries, symbols, metadata, isins, akas, wiki_name]
Index: []

In [46]:
df_stock_tickers[(df_stock_tickers["symbol"]=='RTN')]

,name,symbol,country,indices,industries,symbols,metadata,isins,akas,wiki_name
81,Raytheon Company,RTN,United States,"[S&P 100, S&P 500]","[Industrial Goods, Industrials, Aerospace & De...","[{'yahoo': 'RTN1.F', 'google': 'FRA:RTN1', 'cu...","{'founded': 2020, 'employees': 195000}",[],[],NaN

In [47]:
df_stock_tickers[(df_stock_tickers["symbol"]=='RTX')]

Empty DataFrame
Columns: [name, symbol, country, indices, industries, symbols, metadata, isins, akas, wiki_name]
Index: []

In [ ]:
https://www.ishares.com/us/products/239723/ishares-sp-100-etf/1467271812596.ajax?fileType=csv&fileName=OEF_holdings&dataType=fund

In [79]:
url = 'https://www.ishares.com/us/products/239723/ishares-sp-100-etf/1467271812596.ajax?fileType=csv&fileName=OEF_holdings&dataType=fund'
df_sp_100_etf = pd.read_csv(url, skiprows=9)
df_sp_100_etf

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Shares,Price,Location,Exchange,Currency,FX Rate,Market Currency,Accrual Date
0,AAPL,APPLE INC,Information Technology,Equity,"1,307,701,303.35",10.40,"1,307,701,303.35","6,792,195.00",192.53,United States,NASDAQ,USD,1.0,USD,-
1,MSFT,MICROSOFT CORP,Information Technology,Equity,"1,298,464,615.84",10.32,"1,298,464,615.84","3,452,996.00",376.04,United States,NASDAQ,USD,1.0,USD,-
2,AMZN,AMAZON COM INC,Consumer Discretionary,Equity,"641,947,563.58",5.10,"641,947,563.58","4,225,007.00",151.94,United States,NASDAQ,USD,1.0,USD,-
3,NVDA,NVIDIA CORP,Information Technology,Equity,"568,289,711.00",4.52,"568,289,711.00","1,147,550.00",495.22,United States,NASDAQ,USD,1.0,USD,-
4,GOOGL,ALPHABET INC CLASS A,Communication,Equity,"384,074,442.13",3.05,"384,074,442.13","2,749,477.00",139.69,United States,NASDAQ,USD,1.0,USD,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,MSFUT,CASH COLLATERAL MSFUT USD,Cash and/or Derivatives,Cash Collateral and Margins,"1,770,640.00",0.01,"1,770,640.00","1,770,640.00",100.00,United States,-,USD,1.0,USD,"Feb 01, 2009"
104,ESH4,S&P500 EMINI MAR 24,Cash and/or Derivatives,Futures,0.00,0.00,"32,535,000.00",135.00,"4,820.00",-,Index And Options Market,USD,1.0,USD,-
105,MARGIN_USD,FUTURES USD MARGIN BALANCE,Cash and/or Derivatives,Cash Collateral and Margins,"-82,687.50",0.00,"-82,687.50","-82,688.00",100.00,United States,-,USD,1.0,USD,"Jan 01, 2000"
106,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,The content contained herein is owned or licen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
df_sp_100_etf.loc[df_sp_100_etf['Sector'] == 'Cash and/or Derivatives']

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Shares,Price,Location,Exchange,Currency,FX Rate,Market Currency,Accrual Date
90,XTSLA,BLK CSH FND TREASURY SL AGENCY,Cash and/or Derivatives,Money Market,"23,794,575.87",0.19,"23,794,575.87","23,794,576.00",1.00,United States,-,USD,1.0,USD,-
102,USD,USD CASH,Cash and/or Derivatives,Cash,"7,289,349.39",0.06,"7,289,349.39","7,289,349.00",100.00,United States,-,USD,1.0,USD,-
103,MSFUT,CASH COLLATERAL MSFUT USD,Cash and/or Derivatives,Cash Collateral and Margins,"1,770,640.00",0.01,"1,770,640.00","1,770,640.00",100.00,United States,-,USD,1.0,USD,"Feb 01, 2009"
104,ESH4,S&P500 EMINI MAR 24,Cash and/or Derivatives,Futures,0.00,0.00,"32,535,000.00",135.00,"4,820.00",-,Index And Options Market,USD,1.0,USD,-
105,MARGIN_USD,FUTURES USD MARGIN BALANCE,Cash and/or Derivatives,Cash Collateral and Margins,"-82,687.50",0.00,"-82,687.50","-82,688.00",100.00,United States,-,USD,1.0,USD,"Jan 01, 2000"

In [81]:
df_sp_100_etf.iloc[106:108]

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Shares,Price,Location,Exchange,Currency,FX Rate,Market Currency,Accrual Date
106,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,The content contained herein is owned or licen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df_sp_100_etf = df_sp_100_etf.iloc[1:106]
df_sp_100_etf

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Shares,Price,Location,Exchange,Currency,FX Rate,Market Currency,Accrual Date
1,MSFT,MICROSOFT CORP,Information Technology,Equity,"1,298,464,615.84",10.32,"1,298,464,615.84","3,452,996.00",376.04,United States,NASDAQ,USD,1.0,USD,-
2,AMZN,AMAZON COM INC,Consumer Discretionary,Equity,"641,947,563.58",5.10,"641,947,563.58","4,225,007.00",151.94,United States,NASDAQ,USD,1.0,USD,-
3,NVDA,NVIDIA CORP,Information Technology,Equity,"568,289,711.00",4.52,"568,289,711.00","1,147,550.00",495.22,United States,NASDAQ,USD,1.0,USD,-
4,GOOGL,ALPHABET INC CLASS A,Communication,Equity,"384,074,442.13",3.05,"384,074,442.13","2,749,477.00",139.69,United States,NASDAQ,USD,1.0,USD,-
5,META,META PLATFORMS INC CLASS A,Communication,Equity,"365,010,277.24",2.90,"365,010,277.24","1,031,219.00",353.96,United States,NASDAQ,USD,1.0,USD,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,KHC,KRAFT HEINZ,Consumer Staples,Equity,"13,698,982.14",0.11,"13,698,982.14","370,443.00",36.98,United States,NASDAQ,USD,1.0,USD,-
102,USD,USD CASH,Cash and/or Derivatives,Cash,"7,289,349.39",0.06,"7,289,349.39","7,289,349.00",100.00,United States,-,USD,1.0,USD,-
103,MSFUT,CASH COLLATERAL MSFUT USD,Cash and/or Derivatives,Cash Collateral and Margins,"1,770,640.00",0.01,"1,770,640.00","1,770,640.00",100.00,United States,-,USD,1.0,USD,"Feb 01, 2009"
104,ESH4,S&P500 EMINI MAR 24,Cash and/or Derivatives,Futures,0.00,0.00,"32,535,000.00",135.00,"4,820.00",-,Index And Options Market,USD,1.0,USD,-
105,MARGIN_USD,FUTURES USD MARGIN BALANCE,Cash and/or Derivatives,Cash Collateral and Margins,"-82,687.50",0.00,"-82,687.50","-82,688.00",100.00,United States,-,USD,1.0,USD,"Jan 01, 2000"

In [83]:
df_sp_100_etf = df_sp_100_etf.loc[df_sp_100_etf['Sector'] != 'Cash and/or Derivatives']

In [84]:
df_sp_100_etf

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Shares,Price,Location,Exchange,Currency,FX Rate,Market Currency,Accrual Date
1,MSFT,MICROSOFT CORP,Information Technology,Equity,"1,298,464,615.84",10.32,"1,298,464,615.84","3,452,996.00",376.04,United States,NASDAQ,USD,1.0,USD,-
2,AMZN,AMAZON COM INC,Consumer Discretionary,Equity,"641,947,563.58",5.10,"641,947,563.58","4,225,007.00",151.94,United States,NASDAQ,USD,1.0,USD,-
3,NVDA,NVIDIA CORP,Information Technology,Equity,"568,289,711.00",4.52,"568,289,711.00","1,147,550.00",495.22,United States,NASDAQ,USD,1.0,USD,-
4,GOOGL,ALPHABET INC CLASS A,Communication,Equity,"384,074,442.13",3.05,"384,074,442.13","2,749,477.00",139.69,United States,NASDAQ,USD,1.0,USD,-
5,META,META PLATFORMS INC CLASS A,Communication,Equity,"365,010,277.24",2.90,"365,010,277.24","1,031,219.00",353.96,United States,NASDAQ,USD,1.0,USD,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,BK,BANK OF NEW YORK MELLON CORP,Financials,Equity,"18,652,169.55",0.15,"18,652,169.55","358,351.00",52.05,United States,New York Stock Exchange Inc.,USD,1.0,USD,-
98,CHTR,CHARTER COMMUNICATIONS INC CLASS A,Communication,Equity,"18,163,016.40",0.14,"18,163,016.40","46,730.00",388.68,United States,NASDAQ,USD,1.0,USD,-
99,DOW,DOW INC,Materials,Equity,"17,878,004.52",0.14,"17,878,004.52","326,003.00",54.84,United States,New York Stock Exchange Inc.,USD,1.0,USD,-
100,EXC,EXELON CORP,Utilities,Equity,"16,614,879.00",0.13,"16,614,879.00","462,810.00",35.90,United States,NASDAQ,USD,1.0,USD,-
101,KHC,KRAFT HEINZ,Consumer Staples,Equity,"13,698,982.14",0.11,"13,698,982.14","370,443.00",36.98,United States,NASDAQ,USD,1.0,USD,-

In [86]:
df_sp_100_etf = df_sp_100_etf.drop(columns=['Accrual Date', 'Asset Class', 'Weight (%)', 'Notional Value', 'Location', 'Exchange', 'Currency', 'FX Rate', 'Market Currency'])
df_sp_100_etf.head()

,Ticker,Name,Sector,Market Value,Shares,Price
1,MSFT,MICROSOFT CORP,Information Technology,"1,298,464,615.84","3,452,996.00",376.04
2,AMZN,AMAZON COM INC,Consumer Discretionary,"641,947,563.58","4,225,007.00",151.94
3,NVDA,NVIDIA CORP,Information Technology,"568,289,711.00","1,147,550.00",495.22
4,GOOGL,ALPHABET INC CLASS A,Communication,"384,074,442.13","2,749,477.00",139.69
5,META,META PLATFORMS INC CLASS A,Communication,"365,010,277.24","1,031,219.00",353.96